/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

int dyn_mass(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem);
void dyn_mass_incref(void);
void dyn_mass_decref(void);
int dyn_mass_n_out(void);
int dyn_mass_n_in(void);
const char* dyn_mass_name_in(int i);
const char* dyn_mass_name_out(int i);
const int* dyn_mass_sparsity_in(int i);
const int* dyn_mass_sparsity_out(int i);
int dyn_mass_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
