/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

int plimt(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem);
void plimt_incref(void);
void plimt_decref(void);
int plimt_n_out(void);
int plimt_n_in(void);
const char* plimt_name_in(int i);
const char* plimt_name_out(int i);
const int* plimt_sparsity_in(int i);
const int* plimt_sparsity_out(int i);
int plimt_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
